maleta(pale_cyan_,2,posh_black_).
maleta(pale_cyan_,4,wavy_gold_).
maleta(pale_cyan_,2,vibrant_brown_).
maleta(dull_lavender_,3,pale_tomato_).
maleta(light_red_,3,wavy_teal_).
maleta(light_red_,3,plaid_aqua_).
maleta(light_red_,4,drab_lavender_).
maleta(light_red_,2,bright_coral_).
maleta(wavy_green_,3,wavy_indigo_).
maleta(bright_blue_,5,vibrant_tan_).
maleta(dotted_fuchsia_,5,dark_orange_).
maleta(dotted_fuchsia_,1,shiny_coral_).
maleta(pale_tomato_,2,bright_magenta_).
maleta(pale_tomato_,5,dull_lime_).
maleta(light_black_,1,posh_lavender_).
maleta(light_black_,5,dotted_gold_).
maleta(light_black_,4,faded_bronze_).
maleta(wavy_turquoise_,4,pale_teal_).
maleta(wavy_turquoise_,2,dim_brown_).
maleta(wavy_turquoise_,5,muted_lime_).
maleta(striped_red_,4,faded_brown_).
maleta(striped_red_,4,dotted_purple_).
maleta(wavy_silver_,5,muted_chartreuse_).
maleta(wavy_silver_,1,light_silver_).
maleta(wavy_silver_,3,striped_silver_).
maleta(posh_lavender_,5,striped_silver_).
maleta(posh_lavender_,3,wavy_beige_).
maleta(posh_lavender_,3,dim_brown_).
maleta(posh_lavender_,5,clear_indigo_).
maleta(pale_maroon_,1,striped_white_).
maleta(pale_maroon_,4,light_blue_).
maleta(drab_turquoise_,2,shiny_tomato_).
maleta(dark_aqua_,2,plaid_silver_).
maleta(vibrant_coral_,3,wavy_lime_).
maleta(vibrant_coral_,2,shiny_gold_).
maleta(vibrant_coral_,1,dotted_orange_).
maleta(vibrant_coral_,3,muted_indigo_).
maleta(clear_green_,1,clear_olive_).
maleta(striped_indigo_,3,striped_turquoise_).
maleta(clear_lime_,3,mirrored_green_).
maleta(clear_lime_,2,light_tan_).
maleta(drab_bronze_,5,plaid_lavender_).
maleta(drab_bronze_,1,muted_yellow_).
maleta(drab_bronze_,5,vibrant_coral_).
maleta(drab_lavender_,1,posh_tomato_).
maleta(drab_lavender_,4,muted_salmon_).
maleta(drab_lavender_,4,dull_lime_).
maleta(striped_aqua_,1,pale_maroon_).
maleta(wavy_gray_,3,light_tan_).
maleta(wavy_gray_,2,pale_white_).
maleta(wavy_gray_,2,bright_magenta_).
maleta(wavy_gray_,5,muted_salmon_).
maleta(faded_aqua_,1,plaid_salmon_).
maleta(faded_aqua_,4,dotted_yellow_).
maleta(drab_cyan_,1,posh_tomato_).
maleta(drab_cyan_,4,shiny_turquoise_).
maleta(vibrant_blue_,no,other_).
maleta(light_lime_,3,vibrant_purple_).
maleta(clear_gray_,3,mirrored_olive_).
maleta(clear_gray_,3,clear_crimson_).
maleta(clear_gray_,5,dark_orange_).
maleta(clear_gray_,2,dim_gold_).
maleta(bright_magenta_,no,other_).
maleta(wavy_purple_,4,dim_gold_).
maleta(wavy_purple_,5,light_green_).
maleta(muted_bronze_,2,pale_beige_).
maleta(muted_bronze_,2,clear_turquoise_).
maleta(muted_bronze_,5,posh_white_).
maleta(muted_bronze_,1,wavy_gray_).
maleta(striped_violet_,1,light_gold_).
maleta(dull_salmon_,2,posh_gray_).
maleta(dull_salmon_,2,dotted_blue_).
maleta(striped_orange_,3,faded_coral_).
maleta(striped_orange_,3,dotted_lavender_).
maleta(drab_coral_,1,wavy_indigo_).
maleta(drab_coral_,1,dull_black_).
maleta(drab_coral_,3,mirrored_chartreuse_).
maleta(plaid_yellow_,5,faded_cyan_).
maleta(dark_maroon_,2,mirrored_silver_).
maleta(dark_maroon_,5,muted_salmon_).
maleta(dark_maroon_,1,dull_tomato_).
maleta(dark_yellow_,1,drab_maroon_).
maleta(dark_yellow_,5,faded_cyan_).
maleta(dark_yellow_,4,clear_indigo_).
maleta(posh_teal_,3,vibrant_maroon_).
maleta(posh_teal_,3,posh_salmon_).
maleta(mirrored_black_,1,drab_fuchsia_).
maleta(mirrored_black_,2,posh_red_).
maleta(drab_salmon_,2,dull_plum_).
maleta(muted_green_,4,plaid_gray_).
maleta(muted_green_,2,dim_turquoise_).
maleta(muted_green_,2,dull_coral_).
maleta(muted_green_,4,dim_white_).
maleta(bright_indigo_,1,bright_turquoise_).
maleta(bright_indigo_,4,dark_beige_).
maleta(wavy_fuchsia_,1,clear_violet_).
maleta(wavy_fuchsia_,4,striped_bronze_).
maleta(wavy_fuchsia_,1,mirrored_indigo_).
maleta(wavy_fuchsia_,1,shiny_cyan_).
maleta(bright_brown_,5,dark_purple_).
maleta(dull_turquoise_,3,dim_yellow_).
maleta(dull_turquoise_,2,dim_indigo_).
maleta(pale_coral_,4,posh_indigo_).
maleta(striped_green_,4,dull_green_).
maleta(striped_green_,5,dotted_turquoise_).
maleta(striped_green_,3,pale_red_).
maleta(striped_green_,2,dark_gold_).
maleta(faded_maroon_,3,dim_green_).
maleta(faded_maroon_,4,wavy_purple_).
maleta(vibrant_lime_,3,shiny_fuchsia_).
maleta(vibrant_lime_,1,pale_red_).
maleta(vibrant_lime_,1,vibrant_bronze_).
maleta(shiny_plum_,2,bright_maroon_).
maleta(shiny_plum_,5,dull_tomato_).
maleta(shiny_plum_,2,plaid_salmon_).
maleta(shiny_plum_,3,bright_lime_).
maleta(faded_silver_,1,posh_turquoise_).
maleta(faded_silver_,5,posh_white_).
maleta(faded_silver_,5,wavy_lime_).
maleta(faded_silver_,3,shiny_coral_).
maleta(mirrored_tomato_,3,dotted_tomato_).
maleta(mirrored_tomato_,4,vibrant_blue_).
maleta(mirrored_tomato_,4,dull_yellow_).
maleta(mirrored_tomato_,5,clear_chartreuse_).
maleta(pale_red_,5,vibrant_indigo_).
maleta(pale_red_,4,vibrant_red_).
maleta(pale_red_,3,bright_magenta_).
maleta(pale_red_,3,dim_indigo_).
maleta(drab_blue_,2,bright_magenta_).
maleta(dim_purple_,4,drab_lavender_).
maleta(dim_purple_,4,plaid_yellow_).
maleta(dim_purple_,5,dull_white_).
maleta(dim_purple_,3,clear_white_).
maleta(dim_red_,5,striped_silver_).
maleta(dim_red_,1,shiny_red_).
maleta(dim_lime_,5,plaid_bronze_).
maleta(dim_lime_,5,drab_salmon_).
maleta(mirrored_beige_,3,bright_tomato_).
maleta(mirrored_beige_,2,dull_lime_).
maleta(bright_lime_,5,clear_chartreuse_).
maleta(clear_chartreuse_,1,muted_white_).
maleta(clear_chartreuse_,1,vibrant_bronze_).
maleta(clear_chartreuse_,2,vibrant_maroon_).
maleta(clear_chartreuse_,4,clear_lime_).
maleta(dotted_indigo_,4,pale_olive_).
maleta(dotted_indigo_,1,bright_violet_).
maleta(dotted_indigo_,3,drab_gray_).
maleta(striped_crimson_,3,muted_salmon_).
maleta(plaid_green_,3,posh_tomato_).
maleta(dim_brown_,3,striped_teal_).
maleta(dim_brown_,3,vibrant_aqua_).
maleta(dim_brown_,3,plaid_yellow_).
maleta(faded_turquoise_,2,dim_blue_).
maleta(faded_turquoise_,3,clear_green_).
maleta(faded_turquoise_,3,striped_bronze_).
maleta(faded_turquoise_,2,dim_beige_).
maleta(dotted_coral_,2,vibrant_silver_).
maleta(dotted_coral_,3,plaid_crimson_).
maleta(dotted_coral_,4,dull_silver_).
maleta(dotted_coral_,1,muted_blue_).
maleta(mirrored_magenta_,3,striped_teal_).
maleta(mirrored_magenta_,1,mirrored_black_).
maleta(mirrored_magenta_,4,shiny_black_).
maleta(shiny_gray_,3,bright_magenta_).
maleta(mirrored_violet_,5,drab_blue_).
maleta(mirrored_violet_,5,dark_brown_).
maleta(dark_beige_,2,vibrant_blue_).
maleta(dark_beige_,2,bright_magenta_).
maleta(dark_beige_,1,dim_indigo_).
maleta(dark_bronze_,3,vibrant_chartreuse_).
maleta(dark_bronze_,2,posh_turquoise_).
maleta(dark_bronze_,4,faded_aqua_).
maleta(clear_turquoise_,1,mirrored_green_).
maleta(clear_turquoise_,1,faded_indigo_).
maleta(clear_turquoise_,4,shiny_aqua_).
maleta(clear_turquoise_,4,dim_tomato_).
maleta(dark_silver_,5,posh_purple_).
maleta(dark_silver_,4,dull_silver_).
maleta(dull_tan_,2,striped_brown_).
maleta(dull_tan_,3,vibrant_salmon_).
maleta(dull_tan_,1,drab_gold_).
maleta(mirrored_gray_,2,dim_white_).
maleta(mirrored_gray_,4,muted_white_).
maleta(mirrored_gray_,1,muted_orange_).
maleta(mirrored_gray_,3,muted_magenta_).
maleta(faded_black_,3,faded_aqua_).
maleta(faded_black_,4,drab_white_).
maleta(faded_black_,2,dull_lavender_).
maleta(faded_black_,1,bright_purple_).
maleta(light_fuchsia_,3,pale_magenta_).
maleta(wavy_lavender_,no,other_).
maleta(dull_black_,1,mirrored_teal_).
maleta(vibrant_chartreuse_,1,dull_violet_).
maleta(vibrant_chartreuse_,4,posh_turquoise_).
maleta(posh_yellow_,5,wavy_gold_).
maleta(shiny_teal_,2,drab_salmon_).
maleta(shiny_teal_,5,striped_crimson_).
maleta(plaid_fuchsia_,3,dim_brown_).
maleta(plaid_fuchsia_,2,posh_bronze_).
maleta(plaid_fuchsia_,1,striped_aqua_).
maleta(plaid_fuchsia_,1,shiny_chartreuse_).
maleta(faded_yellow_,1,dotted_tan_).
maleta(faded_yellow_,3,dark_coral_).
maleta(mirrored_orange_,3,pale_coral_).
maleta(wavy_indigo_,5,shiny_coral_).
maleta(wavy_indigo_,2,shiny_yellow_).
maleta(wavy_indigo_,2,striped_brown_).
maleta(dotted_salmon_,1,drab_turquoise_).
maleta(dotted_salmon_,1,vibrant_lime_).
maleta(dotted_salmon_,3,dull_chartreuse_).
maleta(dotted_salmon_,1,vibrant_maroon_).
maleta(dull_magenta_,3,shiny_coral_).
maleta(dull_magenta_,5,dull_violet_).
maleta(dull_magenta_,5,mirrored_violet_).
maleta(shiny_tomato_,1,dim_salmon_).
maleta(shiny_tomato_,1,dim_olive_).
maleta(drab_gold_,3,drab_maroon_).
maleta(drab_gold_,1,dotted_black_).
maleta(drab_gold_,4,plaid_orange_).
maleta(bright_yellow_,4,muted_teal_).
maleta(bright_yellow_,1,faded_maroon_).
maleta(bright_yellow_,5,posh_chartreuse_).
maleta(bright_yellow_,5,plaid_indigo_).
maleta(dull_plum_,1,shiny_salmon_).
maleta(dull_plum_,3,light_tan_).
maleta(posh_gray_,3,muted_lime_).
maleta(posh_gray_,2,dotted_green_).
maleta(clear_violet_,5,vibrant_maroon_).
maleta(dotted_bronze_,3,light_tan_).
maleta(dotted_bronze_,4,shiny_yellow_).
maleta(dotted_bronze_,3,mirrored_brown_).
maleta(dotted_bronze_,1,plaid_yellow_).
maleta(mirrored_lime_,2,bright_teal_).
maleta(mirrored_lime_,2,dim_gold_).
maleta(mirrored_lime_,2,dull_tomato_).
maleta(mirrored_lime_,3,wavy_green_).
maleta(shiny_indigo_,3,dull_silver_).
maleta(shiny_indigo_,2,dim_cyan_).
maleta(shiny_indigo_,2,striped_magenta_).
maleta(vibrant_crimson_,2,light_chartreuse_).
maleta(dim_magenta_,5,plaid_olive_).
maleta(dim_magenta_,2,muted_green_).
maleta(dim_magenta_,4,bright_crimson_).
maleta(dim_blue_,1,bright_silver_).
maleta(dim_blue_,2,shiny_gray_).
maleta(plaid_teal_,4,shiny_aqua_).
maleta(plaid_teal_,1,dull_fuchsia_).
maleta(plaid_teal_,4,bright_lime_).
maleta(dull_teal_,2,dotted_black_).
maleta(plaid_gray_,5,muted_brown_).
maleta(pale_teal_,5,striped_olive_).
maleta(pale_teal_,1,dotted_fuchsia_).
maleta(pale_teal_,3,dark_teal_).
maleta(pale_teal_,2,dim_purple_).
maleta(clear_beige_,3,pale_lime_).
maleta(clear_beige_,4,striped_aqua_).
maleta(clear_beige_,3,mirrored_red_).
maleta(mirrored_green_,4,mirrored_olive_).
maleta(mirrored_green_,5,dim_salmon_).
maleta(mirrored_green_,4,vibrant_bronze_).
maleta(plaid_aqua_,2,pale_white_).
maleta(plaid_aqua_,1,dull_plum_).
maleta(plaid_aqua_,4,mirrored_olive_).
maleta(plaid_aqua_,3,dim_maroon_).
maleta(pale_aqua_,5,bright_salmon_).
maleta(pale_aqua_,4,vibrant_silver_).
maleta(pale_aqua_,2,light_orange_).
maleta(plaid_crimson_,3,striped_magenta_).
maleta(mirrored_red_,5,dull_coral_).
maleta(mirrored_red_,5,pale_yellow_).
maleta(mirrored_red_,5,drab_maroon_).
maleta(mirrored_red_,2,dim_gray_).
maleta(pale_black_,1,light_red_).
maleta(pale_black_,4,faded_teal_).
maleta(dim_turquoise_,5,faded_purple_).
maleta(dim_turquoise_,4,wavy_fuchsia_).
maleta(dim_turquoise_,3,vibrant_purple_).
maleta(dim_turquoise_,2,pale_beige_).
maleta(dim_lavender_,1,light_blue_).
maleta(pale_gray_,3,mirrored_red_).
maleta(pale_gray_,5,light_indigo_).
maleta(clear_magenta_,5,bright_gold_).
maleta(clear_magenta_,5,dim_lavender_).
maleta(clear_magenta_,1,wavy_lavender_).
maleta(dull_gold_,4,dull_fuchsia_).
maleta(dull_gold_,3,vibrant_tan_).
maleta(dim_salmon_,5,dull_yellow_).
maleta(dim_salmon_,4,pale_beige_).
maleta(drab_magenta_,2,vibrant_salmon_).
maleta(vibrant_green_,3,bright_purple_).
maleta(vibrant_green_,5,wavy_brown_).
maleta(vibrant_green_,5,dotted_gray_).
maleta(vibrant_green_,1,posh_bronze_).
maleta(dull_brown_,1,wavy_tan_).
maleta(dull_brown_,1,shiny_salmon_).
maleta(clear_white_,5,bright_lime_).
maleta(clear_white_,3,light_tan_).
maleta(dotted_lavender_,5,wavy_cyan_).
maleta(dotted_lavender_,2,dark_indigo_).
maleta(dotted_lavender_,4,shiny_gold_).
maleta(dotted_purple_,5,dull_teal_).
maleta(dotted_purple_,3,shiny_plum_).
maleta(drab_yellow_,3,faded_beige_).
maleta(drab_yellow_,3,light_silver_).
maleta(dark_orange_,5,bright_lime_).
maleta(dotted_cyan_,1,vibrant_lime_).
maleta(dotted_cyan_,1,wavy_maroon_).
maleta(dotted_cyan_,2,dull_tan_).
maleta(dotted_cyan_,5,shiny_salmon_).
maleta(posh_indigo_,5,dull_yellow_).
maleta(posh_indigo_,1,vibrant_bronze_).
maleta(dull_chartreuse_,2,wavy_lavender_).
maleta(dull_chartreuse_,5,vibrant_blue_).
maleta(posh_blue_,3,wavy_maroon_).
maleta(dim_teal_,3,muted_turquoise_).
maleta(dim_teal_,1,vibrant_black_).
maleta(dim_teal_,5,dotted_tomato_).
maleta(pale_purple_,1,striped_olive_).
maleta(drab_chartreuse_,1,clear_orange_).
maleta(drab_chartreuse_,2,plaid_turquoise_).
maleta(drab_chartreuse_,2,drab_maroon_).
maleta(plaid_white_,4,plaid_indigo_).
maleta(plaid_white_,5,vibrant_lime_).
maleta(vibrant_bronze_,5,vibrant_blue_).
maleta(vibrant_bronze_,1,drab_blue_).
maleta(vibrant_bronze_,1,dull_lime_).
maleta(bright_bronze_,3,muted_magenta_).
maleta(bright_bronze_,3,dotted_black_).
maleta(bright_bronze_,1,pale_lime_).
maleta(bright_bronze_,2,dull_violet_).
maleta(dark_indigo_,3,bright_maroon_).
maleta(muted_lavender_,1,light_white_).
maleta(muted_lavender_,2,clear_white_).
maleta(muted_lavender_,2,posh_white_).
maleta(muted_lavender_,3,dim_purple_).
maleta(vibrant_violet_,5,dull_magenta_).
maleta(vibrant_violet_,4,posh_coral_).
maleta(drab_beige_,2,plaid_magenta_).
maleta(drab_beige_,2,muted_bronze_).
maleta(drab_beige_,2,muted_purple_).
maleta(drab_plum_,4,mirrored_tomato_).
maleta(drab_plum_,3,light_lavender_).
maleta(drab_plum_,3,mirrored_green_).
maleta(drab_plum_,5,muted_salmon_).
maleta(mirrored_fuchsia_,1,mirrored_tomato_).
maleta(mirrored_fuchsia_,5,dotted_black_).
maleta(mirrored_fuchsia_,2,posh_white_).
maleta(pale_crimson_,4,light_plum_).
maleta(dotted_black_,3,bright_maroon_).
maleta(wavy_tomato_,1,dim_black_).
maleta(wavy_tomato_,5,vibrant_coral_).
maleta(wavy_tomato_,1,mirrored_purple_).
maleta(bright_aqua_,5,pale_lime_).
maleta(bright_aqua_,3,striped_teal_).
maleta(vibrant_purple_,2,clear_turquoise_).
maleta(vibrant_purple_,4,vibrant_bronze_).
maleta(vibrant_purple_,1,dark_lime_).
maleta(vibrant_purple_,3,clear_crimson_).
maleta(vibrant_tan_,4,posh_black_).
maleta(plaid_turquoise_,2,dotted_violet_).
maleta(plaid_turquoise_,5,mirrored_plum_).
maleta(dim_violet_,3,dotted_orange_).
maleta(bright_tan_,2,dark_indigo_).
maleta(bright_tan_,4,faded_purple_).
maleta(bright_tan_,4,dim_blue_).
maleta(muted_chartreuse_,4,dotted_black_).
maleta(muted_chartreuse_,5,mirrored_tomato_).
maleta(muted_gold_,2,wavy_gray_).
maleta(muted_gold_,4,clear_gold_).
maleta(muted_gold_,1,shiny_gold_).
maleta(dull_indigo_,3,mirrored_maroon_).
maleta(clear_aqua_,4,dim_plum_).
maleta(clear_aqua_,5,bright_bronze_).
maleta(muted_maroon_,1,striped_crimson_).
maleta(muted_maroon_,3,vibrant_aqua_).
maleta(muted_blue_,4,clear_magenta_).
maleta(muted_blue_,4,pale_bronze_).
maleta(muted_blue_,2,dull_black_).
maleta(muted_blue_,4,striped_olive_).
maleta(drab_aqua_,3,faded_crimson_).
maleta(shiny_olive_,4,shiny_salmon_).
maleta(shiny_olive_,2,wavy_plum_).
maleta(shiny_olive_,4,pale_bronze_).
maleta(shiny_olive_,3,posh_gold_).
maleta(striped_bronze_,4,plaid_olive_).
maleta(striped_bronze_,4,plaid_indigo_).
maleta(striped_bronze_,1,pale_white_).
maleta(striped_bronze_,3,striped_magenta_).
maleta(mirrored_gold_,2,faded_lavender_).
maleta(faded_blue_,1,plaid_bronze_).
maleta(faded_blue_,3,dim_olive_).
maleta(faded_blue_,2,wavy_crimson_).
maleta(faded_blue_,4,plaid_silver_).
maleta(plaid_lime_,2,dim_yellow_).
maleta(mirrored_brown_,4,light_crimson_).
maleta(plaid_red_,5,shiny_aqua_).
maleta(plaid_red_,5,wavy_lavender_).
maleta(plaid_red_,1,posh_beige_).
maleta(mirrored_coral_,4,mirrored_lime_).
maleta(mirrored_coral_,5,muted_orange_).
maleta(mirrored_coral_,5,dotted_salmon_).
maleta(mirrored_coral_,1,faded_purple_).
maleta(mirrored_olive_,2,vibrant_blue_).
maleta(pale_orange_,4,wavy_lime_).
maleta(drab_maroon_,1,shiny_yellow_).
maleta(drab_maroon_,3,dull_yellow_).
maleta(drab_maroon_,1,wavy_lavender_).
maleta(drab_maroon_,2,dim_salmon_).
maleta(drab_purple_,5,bright_tomato_).
maleta(drab_purple_,4,striped_bronze_).
maleta(drab_purple_,2,bright_chartreuse_).
maleta(drab_purple_,2,dark_violet_).
maleta(striped_lime_,5,posh_turquoise_).
maleta(striped_lime_,1,dim_purple_).
maleta(wavy_beige_,5,shiny_tomato_).
maleta(wavy_beige_,3,drab_lavender_).
maleta(wavy_beige_,1,shiny_orange_).
maleta(bright_gold_,5,vibrant_red_).
maleta(bright_gold_,1,shiny_orange_).
maleta(bright_gold_,3,striped_bronze_).
maleta(muted_magenta_,4,light_olive_).
maleta(muted_magenta_,3,dotted_tan_).
maleta(dark_lime_,5,wavy_lavender_).
maleta(dark_lime_,4,clear_maroon_).
maleta(dark_lime_,2,striped_beige_).
maleta(dark_lime_,4,plaid_salmon_).
maleta(pale_silver_,3,faded_lavender_).
maleta(pale_silver_,2,dotted_purple_).
maleta(pale_silver_,3,wavy_crimson_).
maleta(posh_turquoise_,5,dim_yellow_).
maleta(posh_turquoise_,4,posh_lime_).
maleta(posh_turquoise_,5,shiny_orange_).
maleta(shiny_coral_,2,dull_tomato_).
maleta(dim_tomato_,3,shiny_aqua_).
maleta(dim_tomato_,3,light_cyan_).
maleta(plaid_tomato_,3,faded_indigo_).
maleta(clear_tan_,3,mirrored_indigo_).
maleta(wavy_maroon_,1,dark_silver_).
maleta(drab_teal_,5,muted_salmon_).
maleta(drab_teal_,4,plaid_yellow_).
maleta(drab_teal_,4,bright_red_).
maleta(drab_teal_,2,posh_teal_).
maleta(dim_plum_,5,posh_salmon_).
maleta(dim_plum_,5,faded_purple_).
maleta(dim_plum_,2,posh_brown_).
maleta(bright_fuchsia_,2,dark_beige_).
maleta(bright_fuchsia_,3,faded_yellow_).
maleta(clear_silver_,2,plaid_tomato_).
maleta(clear_silver_,4,muted_chartreuse_).
maleta(shiny_purple_,5,muted_lavender_).
maleta(shiny_purple_,2,clear_turquoise_).
maleta(shiny_purple_,4,muted_teal_).
maleta(dark_red_,3,plaid_plum_).
maleta(dark_red_,2,dim_indigo_).
maleta(dark_red_,2,wavy_gray_).
maleta(dark_white_,4,muted_bronze_).
maleta(dark_white_,5,mirrored_gold_).
maleta(dark_white_,3,plaid_lavender_).
maleta(drab_silver_,1,dark_gold_).
maleta(drab_silver_,3,muted_white_).
maleta(dark_green_,3,posh_turquoise_).
maleta(striped_white_,1,vibrant_maroon_).
maleta(striped_white_,1,shiny_salmon_).
maleta(striped_lavender_,1,light_tomato_).
maleta(striped_lavender_,5,light_lime_).
maleta(striped_lavender_,1,posh_gold_).
maleta(mirrored_tan_,2,posh_fuchsia_).
maleta(pale_salmon_,4,shiny_blue_).
maleta(dark_black_,1,dotted_coral_).
maleta(dark_black_,1,faded_crimson_).
maleta(dark_black_,4,drab_violet_).
maleta(dark_black_,5,clear_chartreuse_).
maleta(vibrant_red_,1,dim_gold_).
maleta(vibrant_red_,2,dull_yellow_).
maleta(vibrant_red_,1,faded_brown_).
maleta(vibrant_red_,4,light_cyan_).
maleta(pale_turquoise_,5,clear_cyan_).
maleta(bright_olive_,1,clear_turquoise_).
maleta(bright_olive_,4,bright_teal_).
maleta(bright_olive_,3,striped_maroon_).
maleta(bright_olive_,1,striped_gold_).
maleta(shiny_green_,5,dim_lime_).
maleta(shiny_green_,3,wavy_brown_).
maleta(shiny_green_,2,faded_magenta_).
maleta(shiny_green_,5,drab_maroon_).
maleta(vibrant_tomato_,3,striped_plum_).
maleta(vibrant_tomato_,2,vibrant_maroon_).
maleta(vibrant_tomato_,4,muted_silver_).
maleta(vibrant_tomato_,3,striped_chartreuse_).
maleta(vibrant_yellow_,3,pale_beige_).
maleta(vibrant_yellow_,4,dim_orange_).
maleta(vibrant_yellow_,4,dotted_cyan_).
maleta(muted_aqua_,3,vibrant_purple_).
maleta(dull_orange_,2,striped_gray_).
maleta(dull_orange_,3,vibrant_bronze_).
maleta(dull_orange_,2,bright_turquoise_).
maleta(wavy_cyan_,2,drab_maroon_).
maleta(wavy_cyan_,4,shiny_aqua_).
maleta(wavy_cyan_,5,clear_lime_).
maleta(faded_tan_,3,muted_turquoise_).
maleta(faded_tan_,2,plaid_purple_).
maleta(faded_tan_,3,clear_crimson_).
maleta(light_maroon_,5,wavy_chartreuse_).
maleta(light_maroon_,3,mirrored_silver_).
maleta(light_maroon_,5,muted_plum_).
maleta(light_maroon_,2,mirrored_blue_).
maleta(shiny_lavender_,1,dark_silver_).
maleta(shiny_lavender_,5,clear_teal_).
maleta(shiny_lavender_,5,dark_red_).
maleta(shiny_lavender_,4,faded_red_).
maleta(striped_fuchsia_,4,clear_gold_).
maleta(striped_fuchsia_,3,bright_magenta_).
maleta(striped_fuchsia_,3,bright_aqua_).
maleta(striped_plum_,4,bright_lime_).
maleta(striped_plum_,5,dotted_black_).
maleta(striped_plum_,5,drab_beige_).
maleta(dotted_red_,4,dim_gold_).
maleta(dotted_red_,3,dim_indigo_).
maleta(dotted_red_,4,striped_olive_).
maleta(dotted_red_,5,dim_white_).
maleta(mirrored_chartreuse_,5,posh_tomato_).
maleta(dim_white_,5,clear_maroon_).
maleta(muted_black_,2,posh_turquoise_).
maleta(muted_black_,3,clear_lavender_).
maleta(muted_black_,2,shiny_aqua_).
maleta(muted_black_,2,pale_red_).
maleta(muted_silver_,4,striped_white_).
maleta(muted_silver_,5,dotted_tomato_).
maleta(muted_silver_,4,mirrored_fuchsia_).
maleta(muted_silver_,2,clear_maroon_).
maleta(dotted_lime_,1,muted_aqua_).
maleta(dotted_lime_,3,mirrored_tan_).
maleta(faded_chartreuse_,4,vibrant_violet_).
maleta(faded_chartreuse_,5,faded_magenta_).
maleta(faded_chartreuse_,5,dim_teal_).
maleta(faded_chartreuse_,2,dim_green_).
maleta(light_turquoise_,1,dotted_purple_).
maleta(plaid_cyan_,1,bright_magenta_).
maleta(plaid_cyan_,2,wavy_chartreuse_).
maleta(plaid_cyan_,5,vibrant_silver_).
maleta(plaid_cyan_,3,pale_crimson_).
maleta(dull_maroon_,5,dim_black_).
maleta(wavy_violet_,1,faded_yellow_).
maleta(vibrant_teal_,5,dim_lime_).
maleta(vibrant_teal_,2,vibrant_gold_).
maleta(vibrant_teal_,2,dim_beige_).
maleta(pale_fuchsia_,3,striped_olive_).
maleta(light_brown_,3,shiny_chartreuse_).
maleta(light_brown_,2,wavy_purple_).
maleta(dull_green_,3,striped_orange_).
maleta(dull_green_,2,posh_indigo_).
maleta(dull_green_,3,faded_blue_).
maleta(dark_blue_,5,striped_magenta_).
maleta(dark_blue_,3,striped_gray_).
maleta(dark_blue_,4,pale_coral_).
maleta(mirrored_lavender_,3,posh_black_).
maleta(shiny_brown_,5,dotted_magenta_).
maleta(shiny_brown_,4,dim_chartreuse_).
maleta(shiny_brown_,1,posh_cyan_).
maleta(muted_brown_,3,dull_black_).
maleta(muted_brown_,3,pale_maroon_).
maleta(muted_brown_,5,posh_brown_).
maleta(muted_brown_,2,striped_gray_).
maleta(faded_orange_,1,dark_orange_).
maleta(muted_fuchsia_,3,plaid_salmon_).
maleta(clear_plum_,3,shiny_red_).
maleta(clear_plum_,4,dim_silver_).
maleta(bright_coral_,4,pale_yellow_).
maleta(bright_coral_,2,muted_magenta_).
maleta(bright_coral_,2,bright_chartreuse_).
maleta(bright_coral_,3,light_olive_).
maleta(muted_coral_,4,striped_green_).
maleta(drab_olive_,3,shiny_salmon_).
maleta(drab_olive_,4,clear_cyan_).
maleta(dim_silver_,2,shiny_plum_).
maleta(wavy_plum_,3,mirrored_fuchsia_).
maleta(wavy_plum_,5,pale_maroon_).
maleta(wavy_plum_,5,posh_salmon_).
maleta(plaid_coral_,1,mirrored_gold_).
maleta(posh_beige_,3,mirrored_maroon_).
maleta(posh_beige_,3,drab_chartreuse_).
maleta(posh_beige_,3,dark_salmon_).
maleta(posh_beige_,1,clear_green_).
maleta(drab_green_,1,bright_teal_).
maleta(drab_green_,3,muted_chartreuse_).
maleta(bright_crimson_,3,striped_orange_).
maleta(bright_crimson_,4,wavy_plum_).
maleta(posh_chartreuse_,5,clear_white_).
maleta(posh_chartreuse_,3,light_red_).
maleta(dim_gray_,1,mirrored_fuchsia_).
maleta(dim_gray_,3,muted_teal_).
maleta(dim_gray_,4,clear_maroon_).
maleta(dim_gray_,5,striped_white_).
maleta(striped_brown_,2,muted_orange_).
maleta(dim_tan_,3,clear_gold_).
maleta(dim_tan_,5,clear_salmon_).
maleta(dim_tan_,2,dark_chartreuse_).
maleta(striped_magenta_,2,plaid_indigo_).
maleta(striped_magenta_,5,drab_lavender_).
maleta(striped_magenta_,2,dotted_fuchsia_).
maleta(striped_magenta_,4,shiny_aqua_).
maleta(dotted_violet_,3,dull_tomato_).
maleta(dotted_tan_,1,dark_orange_).
maleta(dotted_tan_,2,drab_blue_).
maleta(shiny_beige_,1,drab_gold_).
maleta(light_plum_,5,plaid_tomato_).
maleta(light_plum_,5,wavy_gray_).
maleta(light_plum_,1,dull_tomato_).
maleta(muted_indigo_,3,dim_salmon_).
maleta(clear_red_,3,mirrored_beige_).
maleta(mirrored_silver_,2,wavy_plum_).
maleta(mirrored_silver_,4,vibrant_magenta_).
maleta(dark_lavender_,2,wavy_violet_).
maleta(dark_lavender_,5,muted_green_).
maleta(dark_lavender_,2,dim_purple_).
maleta(clear_teal_,4,wavy_crimson_).
maleta(light_purple_,5,faded_black_).
maleta(light_salmon_,3,vibrant_beige_).
maleta(light_salmon_,3,striped_white_).
maleta(light_salmon_,5,pale_magenta_).
maleta(light_salmon_,5,muted_blue_).
maleta(dull_gray_,5,dim_lavender_).
maleta(posh_aqua_,1,light_olive_).
maleta(posh_aqua_,4,mirrored_purple_).
maleta(posh_aqua_,4,vibrant_gold_).
maleta(posh_aqua_,1,shiny_aqua_).
maleta(pale_chartreuse_,5,faded_indigo_).
maleta(striped_cyan_,1,shiny_olive_).
maleta(striped_cyan_,3,bright_tomato_).
maleta(striped_cyan_,1,faded_beige_).
maleta(clear_coral_,5,clear_violet_).
maleta(clear_coral_,1,plaid_tomato_).
maleta(bright_cyan_,3,mirrored_violet_).
maleta(bright_cyan_,5,plaid_magenta_).
maleta(bright_cyan_,4,vibrant_bronze_).
maleta(posh_tomato_,3,shiny_aqua_).
maleta(posh_tomato_,1,pale_beige_).
maleta(bright_lavender_,4,clear_beige_).
maleta(bright_lavender_,2,faded_lavender_).
maleta(bright_lavender_,3,faded_aqua_).
maleta(bright_lavender_,5,pale_purple_).
maleta(dotted_teal_,5,plaid_salmon_).
maleta(dotted_teal_,1,posh_turquoise_).
maleta(dotted_teal_,2,muted_silver_).
maleta(clear_tomato_,5,bright_indigo_).
maleta(dotted_silver_,2,mirrored_indigo_).
maleta(plaid_plum_,4,light_crimson_).
maleta(wavy_magenta_,2,posh_indigo_).
maleta(wavy_magenta_,2,vibrant_indigo_).
maleta(dull_tomato_,4,dull_lime_).
maleta(dull_tomato_,4,faded_brown_).
maleta(vibrant_black_,5,light_crimson_).
maleta(vibrant_black_,5,pale_lavender_).
maleta(vibrant_black_,3,dull_blue_).
maleta(vibrant_black_,2,pale_coral_).
maleta(pale_bronze_,3,vibrant_violet_).
maleta(wavy_lime_,5,shiny_yellow_).
maleta(wavy_lime_,2,pale_white_).
maleta(wavy_lime_,1,clear_gold_).
maleta(wavy_lime_,5,mirrored_chartreuse_).
maleta(striped_gray_,3,shiny_tomato_).
maleta(striped_gray_,3,dull_coral_).
maleta(striped_gray_,1,shiny_aqua_).
maleta(striped_gray_,2,dark_orange_).
maleta(faded_crimson_,4,pale_white_).
maleta(faded_crimson_,3,muted_bronze_).
maleta(faded_crimson_,2,posh_blue_).
maleta(faded_crimson_,3,bright_coral_).
maleta(wavy_orange_,2,shiny_indigo_).
maleta(dotted_white_,1,striped_tan_).
maleta(dotted_white_,4,bright_silver_).
maleta(dotted_white_,1,shiny_fuchsia_).
maleta(dotted_white_,3,posh_gray_).
maleta(posh_bronze_,4,muted_silver_).
maleta(posh_bronze_,1,light_lavender_).
maleta(dotted_magenta_,5,clear_fuchsia_).
maleta(dotted_magenta_,4,faded_indigo_).
maleta(dotted_magenta_,3,dull_turquoise_).
maleta(dotted_magenta_,4,muted_orange_).
maleta(dull_cyan_,3,clear_teal_).
maleta(dull_cyan_,3,dim_white_).
maleta(dull_cyan_,3,dull_tomato_).
maleta(dull_cyan_,5,vibrant_purple_).
maleta(clear_gold_,4,dim_gold_).
maleta(clear_gold_,3,dull_lime_).
maleta(clear_gold_,4,faded_brown_).
maleta(clear_gold_,4,wavy_gray_).
maleta(bright_beige_,3,dull_cyan_).
maleta(bright_beige_,4,bright_indigo_).
maleta(bright_beige_,2,dull_lime_).
maleta(clear_orange_,5,shiny_salmon_).
maleta(plaid_silver_,5,dotted_purple_).
maleta(plaid_silver_,1,dim_maroon_).
maleta(plaid_silver_,3,muted_gold_).
maleta(shiny_white_,1,light_brown_).
maleta(shiny_white_,1,mirrored_lime_).
maleta(dark_gray_,5,shiny_cyan_).
maleta(dark_gray_,2,drab_tomato_).
maleta(drab_white_,4,shiny_tomato_).
maleta(drab_white_,3,shiny_gold_).
maleta(drab_white_,3,dull_lime_).
maleta(drab_white_,3,plaid_orange_).
maleta(vibrant_cyan_,2,wavy_purple_).
maleta(vibrant_cyan_,4,light_gold_).
maleta(vibrant_cyan_,1,pale_indigo_).
maleta(vibrant_cyan_,2,striped_fuchsia_).
maleta(shiny_yellow_,4,shiny_aqua_).
maleta(shiny_yellow_,2,dim_salmon_).
maleta(shiny_yellow_,3,posh_tomato_).
maleta(shiny_yellow_,5,muted_salmon_).
maleta(posh_coral_,2,striped_gray_).
maleta(posh_coral_,4,dark_orange_).
maleta(posh_coral_,5,posh_magenta_).
maleta(clear_salmon_,4,posh_yellow_).
maleta(clear_salmon_,2,pale_violet_).
maleta(clear_salmon_,3,mirrored_violet_).
maleta(posh_olive_,2,mirrored_red_).
maleta(posh_olive_,3,faded_gold_).
maleta(faded_fuchsia_,5,bright_gold_).
maleta(faded_fuchsia_,3,pale_tomato_).
maleta(faded_fuchsia_,2,dotted_bronze_).
maleta(faded_fuchsia_,1,mirrored_green_).
maleta(striped_maroon_,4,posh_maroon_).
maleta(striped_maroon_,4,dim_indigo_).
maleta(striped_maroon_,5,shiny_aqua_).
maleta(striped_maroon_,4,posh_lime_).
maleta(dark_violet_,5,plaid_tomato_).
maleta(dark_violet_,3,bright_lime_).
maleta(dark_violet_,4,light_lavender_).
maleta(dark_violet_,4,dark_brown_).
maleta(dim_maroon_,1,dark_beige_).
maleta(dim_maroon_,4,wavy_gray_).
maleta(dim_maroon_,5,shiny_coral_).
maleta(dim_maroon_,1,pale_white_).
maleta(wavy_crimson_,1,light_tan_).
maleta(wavy_crimson_,5,dark_beige_).
maleta(plaid_magenta_,1,shiny_turquoise_).
maleta(plaid_magenta_,1,dark_lime_).
maleta(plaid_magenta_,5,dim_salmon_).
maleta(clear_indigo_,4,muted_maroon_).
maleta(clear_olive_,5,mirrored_teal_).
maleta(clear_olive_,1,plaid_lime_).
maleta(clear_olive_,3,dull_magenta_).
maleta(clear_olive_,5,wavy_gray_).
maleta(mirrored_white_,3,pale_gold_).
maleta(wavy_blue_,1,dotted_aqua_).
maleta(wavy_blue_,5,dark_green_).
maleta(faded_cyan_,4,wavy_gray_).
maleta(faded_cyan_,5,vibrant_bronze_).
maleta(faded_cyan_,1,mirrored_olive_).
maleta(faded_cyan_,3,drab_blue_).
maleta(faded_gray_,2,drab_brown_).
maleta(faded_gray_,4,dotted_coral_).
maleta(faded_gray_,5,dim_turquoise_).
maleta(faded_gray_,1,mirrored_maroon_).
maleta(dim_coral_,5,shiny_olive_).
maleta(dim_coral_,3,light_plum_).
maleta(vibrant_fuchsia_,5,shiny_chartreuse_).
maleta(vibrant_fuchsia_,5,wavy_bronze_).
maleta(vibrant_fuchsia_,2,bright_red_).
maleta(dotted_tomato_,5,faded_indigo_).
maleta(dotted_tomato_,3,vibrant_maroon_).
maleta(dotted_tomato_,4,shiny_coral_).
maleta(faded_salmon_,3,dull_silver_).
maleta(faded_salmon_,2,wavy_bronze_).
maleta(faded_salmon_,2,drab_teal_).
maleta(vibrant_orange_,1,dotted_beige_).
maleta(muted_violet_,5,posh_lime_).
maleta(striped_tan_,3,muted_lime_).
maleta(drab_violet_,3,vibrant_chartreuse_).
maleta(drab_violet_,5,posh_turquoise_).
maleta(drab_violet_,1,bright_cyan_).
maleta(bright_purple_,2,vibrant_bronze_).
maleta(bright_purple_,3,wavy_beige_).
maleta(bright_purple_,2,plaid_bronze_).
maleta(vibrant_maroon_,no,other_).
maleta(muted_teal_,2,bright_turquoise_).
maleta(bright_plum_,5,dark_gold_).
maleta(bright_plum_,2,shiny_turquoise_).
maleta(bright_plum_,1,dull_yellow_).
maleta(shiny_crimson_,3,wavy_magenta_).
maleta(wavy_teal_,5,faded_indigo_).
maleta(wavy_teal_,4,dotted_gray_).
maleta(wavy_teal_,3,pale_chartreuse_).
maleta(wavy_teal_,3,vibrant_coral_).
maleta(shiny_blue_,2,shiny_salmon_).
maleta(shiny_blue_,4,light_tan_).
maleta(shiny_blue_,1,dim_salmon_).
maleta(mirrored_maroon_,1,drab_fuchsia_).
maleta(mirrored_maroon_,3,dotted_green_).
maleta(mirrored_maroon_,3,muted_white_).
maleta(clear_maroon_,2,vibrant_red_).
maleta(clear_maroon_,5,bright_maroon_).
maleta(clear_maroon_,4,light_olive_).
maleta(bright_salmon_,1,dotted_red_).
maleta(bright_salmon_,4,vibrant_beige_).
maleta(bright_salmon_,3,dark_maroon_).
maleta(bright_salmon_,3,clear_lavender_).
maleta(pale_gold_,3,plaid_olive_).
maleta(faded_lime_,3,faded_maroon_).
maleta(faded_lime_,5,mirrored_aqua_).
maleta(faded_magenta_,4,plaid_orange_).
maleta(faded_magenta_,5,vibrant_violet_).
maleta(faded_magenta_,1,dotted_green_).
maleta(faded_magenta_,3,wavy_crimson_).
maleta(wavy_aqua_,5,drab_yellow_).
maleta(wavy_aqua_,5,posh_bronze_).
maleta(faded_brown_,3,mirrored_green_).
maleta(faded_brown_,5,dim_salmon_).
maleta(faded_brown_,4,vibrant_blue_).
maleta(faded_brown_,1,wavy_gray_).
maleta(dark_purple_,4,pale_beige_).
maleta(dark_purple_,3,drab_lavender_).
maleta(dull_lime_,no,other_).
maleta(light_orange_,1,vibrant_white_).
maleta(light_orange_,1,striped_magenta_).
maleta(mirrored_plum_,1,clear_green_).
maleta(mirrored_plum_,4,faded_blue_).
maleta(vibrant_brown_,4,dark_crimson_).
maleta(vibrant_brown_,5,light_plum_).
maleta(shiny_turquoise_,1,dark_lime_).
maleta(dark_plum_,2,wavy_coral_).
maleta(dark_plum_,2,striped_gray_).
maleta(dark_plum_,4,muted_blue_).
maleta(dark_plum_,2,dull_aqua_).
maleta(shiny_red_,1,plaid_gray_).
maleta(shiny_red_,4,wavy_beige_).
maleta(shiny_red_,5,dark_red_).
maleta(posh_violet_,5,striped_chartreuse_).
maleta(posh_violet_,2,pale_maroon_).
maleta(posh_violet_,1,dull_lime_).
maleta(light_silver_,2,clear_silver_).
maleta(light_silver_,1,dark_indigo_).
maleta(light_silver_,2,dim_salmon_).
maleta(light_silver_,2,drab_salmon_).
maleta(plaid_orange_,4,dim_gold_).
maleta(plaid_orange_,2,bright_magenta_).
maleta(plaid_orange_,4,drab_lavender_).
maleta(vibrant_silver_,5,posh_plum_).
maleta(vibrant_silver_,3,vibrant_aqua_).
maleta(vibrant_silver_,2,light_lavender_).
maleta(faded_tomato_,1,pale_coral_).
maleta(faded_tomato_,2,posh_gold_).
maleta(shiny_silver_,4,faded_orange_).
maleta(shiny_silver_,1,striped_white_).
maleta(shiny_silver_,2,faded_turquoise_).
maleta(shiny_silver_,5,striped_gray_).
maleta(plaid_purple_,2,posh_olive_).
maleta(plaid_purple_,3,pale_maroon_).
maleta(plaid_purple_,3,pale_gold_).
maleta(plaid_purple_,1,faded_white_).
maleta(light_tomato_,2,vibrant_indigo_).
maleta(light_tomato_,4,dark_orange_).
maleta(light_tomato_,5,muted_bronze_).
maleta(light_tomato_,4,plaid_tomato_).
maleta(dull_aqua_,5,bright_lime_).
maleta(drab_red_,5,posh_teal_).
maleta(dotted_gray_,2,vibrant_salmon_).
maleta(dotted_gray_,4,mirrored_chartreuse_).
maleta(dotted_gray_,1,dotted_tomato_).
maleta(dotted_gray_,4,posh_magenta_).
maleta(dull_bronze_,3,mirrored_brown_).
maleta(shiny_aqua_,no,other_).
maleta(dim_gold_,no,other_).
maleta(pale_blue_,4,posh_gray_).
maleta(faded_purple_,5,shiny_blue_).
maleta(faded_purple_,5,plaid_salmon_).
maleta(faded_purple_,4,pale_tomato_).
maleta(faded_purple_,2,dark_gold_).
maleta(striped_teal_,4,mirrored_green_).
maleta(shiny_orange_,4,faded_lavender_).
maleta(shiny_orange_,2,muted_salmon_).
maleta(shiny_orange_,2,dim_indigo_).
maleta(wavy_yellow_,5,clear_silver_).
maleta(wavy_yellow_,2,shiny_brown_).
maleta(vibrant_turquoise_,1,vibrant_magenta_).
maleta(vibrant_turquoise_,4,dull_fuchsia_).
maleta(vibrant_turquoise_,5,mirrored_green_).
maleta(dark_teal_,5,dim_tomato_).
maleta(posh_brown_,3,dark_orange_).
maleta(vibrant_gray_,2,dark_beige_).
maleta(vibrant_gray_,2,wavy_teal_).
maleta(vibrant_gray_,3,light_purple_).
maleta(drab_black_,1,mirrored_maroon_).
maleta(drab_black_,3,pale_silver_).
maleta(drab_black_,3,dark_brown_).
maleta(drab_black_,1,shiny_gray_).
maleta(light_blue_,2,dim_olive_).
maleta(light_blue_,2,striped_magenta_).
maleta(muted_turquoise_,3,dim_lime_).
maleta(muted_turquoise_,3,shiny_coral_).
maleta(faded_red_,5,clear_gray_).
maleta(bright_chartreuse_,4,plaid_teal_).
maleta(bright_chartreuse_,5,drab_salmon_).
maleta(bright_chartreuse_,5,wavy_cyan_).
maleta(light_magenta_,5,light_aqua_).
maleta(light_magenta_,4,light_crimson_).
maleta(light_magenta_,3,dark_yellow_).
maleta(light_magenta_,1,light_tomato_).
maleta(striped_coral_,3,mirrored_white_).
maleta(shiny_maroon_,1,vibrant_red_).
maleta(shiny_maroon_,3,bright_red_).
maleta(striped_yellow_,1,bright_orange_).
maleta(striped_yellow_,2,faded_plum_).
maleta(striped_yellow_,3,light_olive_).
maleta(striped_yellow_,3,shiny_aqua_).
maleta(dull_olive_,2,posh_fuchsia_).
maleta(dull_olive_,2,dull_coral_).
maleta(dull_olive_,2,faded_red_).
maleta(dotted_yellow_,1,drab_salmon_).
maleta(dotted_yellow_,3,pale_fuchsia_).
maleta(light_bronze_,3,drab_cyan_).
maleta(light_bronze_,5,mirrored_orange_).
maleta(light_bronze_,4,plaid_crimson_).
maleta(shiny_chartreuse_,1,wavy_cyan_).
maleta(shiny_chartreuse_,4,shiny_tomato_).
maleta(dull_yellow_,no,other_).
maleta(faded_plum_,5,vibrant_blue_).
maleta(faded_plum_,5,clear_indigo_).
maleta(faded_plum_,5,posh_teal_).
maleta(faded_plum_,4,posh_plum_).
maleta(wavy_salmon_,4,striped_teal_).
maleta(wavy_salmon_,3,wavy_tan_).
maleta(wavy_salmon_,1,clear_white_).
maleta(posh_salmon_,4,dull_chartreuse_).
maleta(posh_salmon_,4,shiny_yellow_).
maleta(posh_salmon_,2,dotted_black_).
maleta(posh_salmon_,3,clear_lime_).
maleta(dull_white_,2,dim_olive_).
maleta(dull_white_,4,vibrant_bronze_).
maleta(dull_white_,4,faded_cyan_).
maleta(shiny_gold_,5,bright_maroon_).
maleta(shiny_gold_,5,shiny_aqua_).
maleta(shiny_gold_,2,clear_lime_).
maleta(shiny_gold_,2,muted_white_).
maleta(posh_plum_,4,posh_purple_).
maleta(posh_plum_,2,wavy_beige_).
maleta(posh_plum_,5,plaid_plum_).
maleta(shiny_magenta_,4,shiny_tan_).
maleta(shiny_magenta_,2,dull_green_).
maleta(shiny_magenta_,3,mirrored_purple_).
maleta(wavy_olive_,4,vibrant_olive_).
maleta(wavy_olive_,2,clear_fuchsia_).
maleta(wavy_olive_,1,light_plum_).
maleta(wavy_olive_,2,dark_violet_).
maleta(muted_lime_,4,posh_white_).
maleta(muted_lime_,4,shiny_tomato_).
maleta(light_indigo_,2,clear_turquoise_).
maleta(light_indigo_,3,vibrant_black_).
maleta(light_indigo_,3,striped_lime_).
maleta(muted_yellow_,3,mirrored_tomato_).
maleta(faded_beige_,5,clear_red_).
maleta(faded_beige_,3,dull_brown_).
maleta(faded_beige_,4,dark_red_).
maleta(faded_beige_,1,vibrant_magenta_).
maleta(striped_turquoise_,2,bright_aqua_).
maleta(striped_turquoise_,5,dim_cyan_).
maleta(striped_turquoise_,1,pale_lavender_).
maleta(pale_beige_,no,other_).
maleta(dull_silver_,3,bright_lime_).
maleta(dull_silver_,2,pale_tomato_).
maleta(dull_silver_,3,mirrored_green_).
maleta(clear_cyan_,1,vibrant_blue_).
maleta(clear_cyan_,2,faded_cyan_).
maleta(clear_cyan_,1,faded_brown_).
maleta(posh_green_,2,vibrant_gray_).
maleta(posh_green_,1,pale_magenta_).
maleta(muted_beige_,2,drab_blue_).
maleta(muted_beige_,3,vibrant_magenta_).
maleta(muted_beige_,5,pale_tomato_).
maleta(bright_silver_,4,dull_brown_).
maleta(bright_silver_,4,vibrant_violet_).
maleta(bright_silver_,4,dim_violet_).
maleta(mirrored_bronze_,2,bright_indigo_).
maleta(mirrored_bronze_,3,shiny_coral_).
maleta(dull_red_,4,dull_plum_).
maleta(dull_red_,1,striped_black_).
maleta(dull_red_,1,dim_teal_).
maleta(dull_red_,4,dim_white_).
maleta(dim_chartreuse_,3,drab_maroon_).
maleta(drab_crimson_,5,dull_turquoise_).
maleta(drab_crimson_,3,posh_gold_).
maleta(drab_crimson_,4,bright_gold_).
maleta(drab_crimson_,2,muted_indigo_).
maleta(wavy_brown_,1,muted_white_).
maleta(plaid_violet_,2,faded_tomato_).
maleta(muted_salmon_,1,light_cyan_).
maleta(muted_salmon_,1,vibrant_blue_).
maleta(mirrored_salmon_,1,dotted_green_).
maleta(mirrored_salmon_,2,plaid_salmon_).
maleta(posh_lime_,1,vibrant_blue_).
maleta(shiny_tan_,2,bright_red_).
maleta(shiny_tan_,1,dim_maroon_).
maleta(shiny_tan_,3,vibrant_salmon_).
maleta(vibrant_aqua_,5,shiny_orange_).
maleta(vibrant_aqua_,2,dull_coral_).
maleta(vibrant_aqua_,4,vibrant_bronze_).
maleta(vibrant_aqua_,5,dark_indigo_).
maleta(posh_magenta_,5,dim_maroon_).
maleta(posh_magenta_,2,wavy_indigo_).
maleta(posh_red_,4,dull_black_).
maleta(posh_red_,2,shiny_tomato_).
maleta(posh_red_,4,faded_beige_).
maleta(mirrored_indigo_,4,faded_magenta_).
maleta(mirrored_indigo_,1,light_red_).
maleta(mirrored_indigo_,3,muted_gray_).
maleta(mirrored_indigo_,2,plaid_lavender_).
maleta(drab_indigo_,4,dull_tan_).
maleta(drab_indigo_,2,dark_coral_).
maleta(vibrant_lavender_,5,posh_turquoise_).
maleta(vibrant_lavender_,4,posh_bronze_).
maleta(vibrant_lavender_,5,light_tomato_).
maleta(mirrored_blue_,1,striped_bronze_).
maleta(mirrored_blue_,4,plaid_salmon_).
maleta(mirrored_blue_,3,posh_lime_).
maleta(mirrored_blue_,4,mirrored_green_).
maleta(plaid_blue_,4,bright_violet_).
maleta(plaid_blue_,5,clear_red_).
maleta(dark_tan_,3,faded_chartreuse_).
maleta(dark_tan_,1,posh_gold_).
maleta(dark_tan_,5,light_chartreuse_).
maleta(bright_teal_,3,pale_yellow_).
maleta(bright_teal_,1,vibrant_white_).
maleta(bright_teal_,3,shiny_salmon_).
maleta(bright_teal_,1,plaid_indigo_).
maleta(dark_gold_,1,mirrored_green_).
maleta(plaid_beige_,5,dim_cyan_).
maleta(pale_plum_,4,striped_olive_).
maleta(pale_plum_,1,mirrored_violet_).
maleta(drab_orange_,1,plaid_cyan_).
maleta(drab_orange_,2,vibrant_green_).
maleta(drab_orange_,4,striped_crimson_).
maleta(drab_orange_,2,posh_teal_).
maleta(faded_teal_,4,muted_salmon_).
maleta(faded_teal_,1,dim_tomato_).
maleta(faded_teal_,5,clear_white_).
maleta(posh_cyan_,3,shiny_gray_).
maleta(posh_cyan_,2,posh_indigo_).
maleta(plaid_tan_,4,plaid_silver_).
maleta(plaid_tan_,2,dark_beige_).
maleta(plaid_tan_,3,plaid_salmon_).
maleta(plaid_tan_,5,light_beige_).
maleta(muted_olive_,5,vibrant_salmon_).
maleta(muted_olive_,2,dull_orange_).
maleta(muted_tan_,5,wavy_gold_).
maleta(muted_tan_,2,striped_orange_).
maleta(muted_tan_,4,plaid_lavender_).
maleta(posh_tan_,3,shiny_lavender_).
maleta(posh_tan_,5,vibrant_red_).
maleta(posh_tan_,4,light_bronze_).
maleta(bright_tomato_,3,dull_lime_).
maleta(bright_tomato_,3,wavy_gray_).
maleta(dark_turquoise_,3,vibrant_coral_).
maleta(dark_turquoise_,4,wavy_beige_).
maleta(faded_indigo_,4,wavy_gray_).
maleta(clear_blue_,2,pale_yellow_).
maleta(light_gold_,5,light_olive_).
maleta(light_gold_,4,clear_white_).
maleta(light_gold_,3,plaid_silver_).
maleta(light_gold_,2,bright_maroon_).
maleta(light_lavender_,2,dotted_black_).
maleta(light_lavender_,4,plaid_tomato_).
maleta(light_lavender_,4,dark_orange_).
maleta(light_lavender_,5,shiny_blue_).
maleta(faded_coral_,5,pale_gold_).
maleta(faded_coral_,4,dull_black_).
maleta(vibrant_salmon_,2,faded_teal_).
maleta(vibrant_salmon_,4,drab_lavender_).
maleta(vibrant_salmon_,5,clear_teal_).
maleta(vibrant_salmon_,1,dim_olive_).
maleta(muted_orange_,1,posh_salmon_).
maleta(muted_orange_,2,light_cyan_).
maleta(muted_orange_,5,shiny_tomato_).
maleta(muted_orange_,4,dim_olive_).
maleta(clear_black_,3,wavy_bronze_).
maleta(clear_black_,4,wavy_lime_).
maleta(clear_black_,4,shiny_black_).
maleta(pale_violet_,1,faded_violet_).
maleta(pale_violet_,3,pale_chartreuse_).
maleta(pale_violet_,5,drab_blue_).
maleta(dotted_plum_,2,muted_chartreuse_).
maleta(dotted_plum_,3,vibrant_turquoise_).
maleta(dotted_plum_,5,posh_brown_).
maleta(plaid_maroon_,1,posh_coral_).
maleta(plaid_maroon_,1,dull_fuchsia_).
maleta(dotted_brown_,1,posh_lime_).
maleta(dotted_brown_,5,dull_turquoise_).
maleta(pale_green_,3,drab_magenta_).
maleta(pale_green_,4,dim_salmon_).
maleta(pale_green_,1,vibrant_chartreuse_).
maleta(dark_tomato_,2,clear_indigo_).
maleta(dark_tomato_,1,light_plum_).
maleta(dark_tomato_,2,dull_turquoise_).
maleta(striped_silver_,5,dark_red_).
maleta(striped_silver_,4,faded_purple_).
maleta(shiny_fuchsia_,2,dark_gold_).
maleta(shiny_fuchsia_,3,dull_tomato_).
maleta(mirrored_aqua_,5,dark_bronze_).
maleta(dim_beige_,5,dull_white_).
maleta(dark_chartreuse_,4,light_crimson_).
maleta(dark_chartreuse_,3,dim_salmon_).
maleta(dark_chartreuse_,2,dark_orange_).
maleta(plaid_chartreuse_,4,drab_blue_).
maleta(dim_green_,4,muted_bronze_).
maleta(dim_green_,1,shiny_indigo_).
maleta(mirrored_crimson_,5,wavy_fuchsia_).
maleta(mirrored_crimson_,2,vibrant_magenta_).
maleta(clear_yellow_,3,plaid_bronze_).
maleta(clear_yellow_,1,light_tan_).
maleta(bright_turquoise_,3,shiny_salmon_).
maleta(drab_brown_,1,vibrant_fuchsia_).
maleta(dim_bronze_,2,dim_aqua_).
maleta(dim_bronze_,4,dim_beige_).
maleta(dim_black_,1,posh_purple_).
maleta(dim_black_,4,mirrored_bronze_).
maleta(dim_black_,5,posh_plum_).
maleta(plaid_gold_,4,posh_silver_).
maleta(plaid_gold_,5,light_turquoise_).
maleta(plaid_gold_,3,vibrant_black_).
maleta(drab_lime_,1,muted_gold_).
maleta(drab_lime_,4,dotted_red_).
maleta(bright_red_,1,dull_yellow_).
maleta(bright_red_,4,mirrored_gold_).
maleta(vibrant_white_,2,dull_lime_).
maleta(vibrant_white_,2,faded_indigo_).
maleta(vibrant_white_,1,faded_brown_).
maleta(vibrant_white_,1,muted_salmon_).
maleta(drab_fuchsia_,3,pale_beige_).
maleta(drab_fuchsia_,3,dark_orange_).
maleta(striped_tomato_,1,dark_lime_).
maleta(striped_tomato_,5,dull_coral_).
maleta(faded_green_,2,wavy_blue_).
maleta(vibrant_olive_,3,bright_tomato_).
maleta(vibrant_olive_,4,wavy_beige_).
maleta(dark_coral_,5,faded_teal_).
maleta(dark_coral_,1,mirrored_tomato_).
maleta(dark_coral_,3,dark_orange_).
maleta(dark_coral_,5,plaid_lime_).
maleta(bright_violet_,4,dark_lime_).
maleta(wavy_tan_,4,light_tan_).
maleta(wavy_tan_,3,vibrant_red_).
maleta(wavy_tan_,2,mirrored_olive_).
maleta(dotted_beige_,5,striped_gray_).
maleta(dotted_beige_,4,posh_plum_).
maleta(dotted_beige_,1,bright_turquoise_).
maleta(dotted_beige_,4,striped_fuchsia_).
maleta(dotted_turquoise_,3,mirrored_green_).
maleta(dotted_turquoise_,4,posh_gold_).
maleta(dotted_turquoise_,5,drab_plum_).
maleta(striped_beige_,1,clear_gold_).
maleta(striped_beige_,1,vibrant_white_).
maleta(striped_beige_,3,faded_cyan_).
maleta(striped_beige_,2,shiny_gold_).
maleta(posh_silver_,2,vibrant_gold_).
maleta(posh_silver_,2,mirrored_violet_).
maleta(mirrored_purple_,2,dim_yellow_).
maleta(mirrored_purple_,2,dull_tomato_).
maleta(shiny_lime_,4,clear_olive_).
maleta(shiny_lime_,4,mirrored_silver_).
maleta(shiny_lime_,1,muted_tomato_).
maleta(muted_cyan_,1,posh_coral_).
maleta(muted_cyan_,5,drab_blue_).
maleta(muted_cyan_,4,wavy_lavender_).
maleta(light_aqua_,1,dark_orange_).
maleta(shiny_cyan_,2,dark_maroon_).
maleta(shiny_cyan_,5,shiny_salmon_).
maleta(shiny_cyan_,5,muted_salmon_).
maleta(shiny_cyan_,2,wavy_bronze_).
maleta(posh_white_,1,posh_fuchsia_).
maleta(vibrant_plum_,4,light_crimson_).
maleta(dotted_blue_,1,shiny_tan_).
maleta(dotted_blue_,3,light_plum_).
maleta(dotted_blue_,5,dotted_gray_).
maleta(posh_maroon_,5,mirrored_violet_).
maleta(dull_violet_,1,faded_teal_).
maleta(dull_violet_,2,wavy_cyan_).
maleta(dull_violet_,3,dull_silver_).
maleta(dull_violet_,3,vibrant_red_).
maleta(posh_gold_,4,muted_salmon_).
maleta(posh_gold_,4,dull_plum_).
maleta(posh_gold_,3,muted_bronze_).
maleta(dim_orange_,2,dull_coral_).
maleta(dim_aqua_,1,drab_maroon_).
maleta(striped_salmon_,4,muted_white_).
maleta(dark_cyan_,3,plaid_maroon_).
maleta(wavy_red_,2,wavy_maroon_).
maleta(wavy_red_,2,vibrant_chartreuse_).
maleta(wavy_red_,5,wavy_salmon_).
maleta(light_yellow_,4,posh_lime_).
maleta(light_yellow_,1,light_white_).
maleta(striped_blue_,5,plaid_magenta_).
maleta(striped_blue_,5,vibrant_gold_).
maleta(dark_olive_,4,dim_maroon_).
maleta(dark_olive_,2,shiny_tan_).
maleta(dark_olive_,5,wavy_green_).
maleta(vibrant_gold_,1,dull_beige_).
maleta(vibrant_gold_,4,posh_turquoise_).
maleta(muted_white_,1,dim_indigo_).
maleta(muted_white_,5,dull_lime_).
maleta(muted_white_,5,shiny_aqua_).
maleta(light_violet_,5,wavy_bronze_).
maleta(pale_olive_,1,dim_gold_).
maleta(pale_olive_,2,shiny_coral_).
maleta(light_gray_,3,bright_gold_).
maleta(dim_indigo_,3,posh_tomato_).
maleta(dim_indigo_,5,pale_tomato_).
maleta(dim_indigo_,4,shiny_aqua_).
maleta(pale_indigo_,4,pale_bronze_).
maleta(pale_indigo_,5,light_chartreuse_).
maleta(muted_red_,3,clear_white_).
maleta(muted_red_,4,dull_lavender_).
maleta(muted_red_,5,muted_purple_).
maleta(plaid_olive_,3,dark_orange_).
maleta(plaid_olive_,3,dim_gold_).
maleta(dotted_maroon_,3,faded_purple_).
maleta(dotted_maroon_,5,light_green_).
maleta(bright_orange_,1,shiny_black_).
maleta(bright_orange_,2,dim_lavender_).
maleta(bright_orange_,1,shiny_olive_).
maleta(wavy_chartreuse_,3,clear_lime_).
maleta(wavy_chartreuse_,4,pale_maroon_).
maleta(mirrored_turquoise_,2,striped_crimson_).
maleta(mirrored_turquoise_,4,vibrant_bronze_).
maleta(mirrored_turquoise_,5,dotted_lavender_).
maleta(mirrored_turquoise_,2,clear_silver_).
maleta(dull_purple_,4,posh_crimson_).
maleta(faded_bronze_,1,clear_fuchsia_).
maleta(faded_bronze_,2,light_fuchsia_).
maleta(faded_bronze_,2,pale_chartreuse_).
maleta(clear_bronze_,3,pale_chartreuse_).
maleta(clear_bronze_,5,dull_tan_).
maleta(clear_bronze_,1,vibrant_tan_).
maleta(vibrant_magenta_,4,shiny_fuchsia_).
maleta(vibrant_magenta_,2,shiny_coral_).
maleta(vibrant_magenta_,3,faded_indigo_).
maleta(vibrant_magenta_,4,pale_tomato_).
maleta(striped_chartreuse_,2,shiny_orange_).
maleta(striped_chartreuse_,3,mirrored_tomato_).
maleta(striped_chartreuse_,1,clear_lime_).
maleta(dotted_green_,1,pale_beige_).
maleta(dotted_green_,2,mirrored_bronze_).
maleta(dotted_green_,2,wavy_crimson_).
maleta(wavy_white_,3,posh_magenta_).
maleta(wavy_white_,3,muted_yellow_).
maleta(wavy_white_,3,wavy_crimson_).
maleta(wavy_white_,4,vibrant_olive_).
maleta(muted_plum_,4,wavy_gold_).
maleta(faded_violet_,3,dark_violet_).
maleta(dull_fuchsia_,4,plaid_indigo_).
maleta(dull_fuchsia_,1,mirrored_brown_).
maleta(dull_fuchsia_,5,clear_lime_).
maleta(bright_green_,3,mirrored_white_).
maleta(bright_green_,5,dotted_silver_).
maleta(shiny_violet_,4,striped_salmon_).
maleta(dim_fuchsia_,3,striped_red_).
maleta(faded_lavender_,3,wavy_tan_).
maleta(faded_lavender_,2,clear_lime_).
maleta(dim_cyan_,4,drab_white_).
maleta(dark_brown_,5,clear_gold_).
maleta(dark_brown_,3,vibrant_blue_).
maleta(clear_lavender_,5,striped_turquoise_).
maleta(clear_lavender_,1,light_crimson_).
maleta(clear_lavender_,5,light_tan_).
maleta(clear_lavender_,2,muted_gold_).
maleta(light_green_,3,striped_silver_).
maleta(light_green_,4,bright_silver_).
maleta(light_green_,2,light_crimson_).
maleta(pale_lavender_,5,clear_violet_).
maleta(dotted_orange_,3,dotted_tomato_).
maleta(dotted_orange_,2,dull_plum_).
maleta(dotted_orange_,5,posh_purple_).
maleta(dotted_orange_,2,drab_turquoise_).
maleta(bright_black_,3,posh_chartreuse_).
maleta(bright_black_,5,wavy_indigo_).
maleta(bright_black_,5,dull_crimson_).
maleta(bright_black_,2,clear_turquoise_).
maleta(dotted_gold_,5,striped_white_).
maleta(dotted_gold_,2,striped_brown_).
maleta(dotted_gold_,3,mirrored_green_).
maleta(dotted_gold_,3,dark_violet_).
maleta(plaid_brown_,3,striped_chartreuse_).
maleta(plaid_brown_,3,striped_black_).
maleta(plaid_brown_,2,bright_chartreuse_).
maleta(wavy_coral_,3,dim_turquoise_).
maleta(wavy_coral_,4,dim_lime_).
maleta(pale_brown_,4,dim_white_).
maleta(pale_brown_,5,bright_fuchsia_).
maleta(pale_brown_,2,clear_orange_).
maleta(mirrored_teal_,4,pale_lavender_).
maleta(mirrored_teal_,5,vibrant_maroon_).
maleta(mirrored_teal_,4,striped_gray_).
maleta(mirrored_teal_,4,vibrant_indigo_).
maleta(posh_orange_,5,posh_magenta_).
maleta(posh_orange_,4,posh_violet_).
maleta(posh_orange_,2,plaid_magenta_).
maleta(posh_orange_,4,muted_cyan_).
maleta(dim_crimson_,3,drab_violet_).
maleta(dim_crimson_,1,dotted_aqua_).
maleta(muted_gray_,4,vibrant_lime_).
maleta(muted_gray_,1,dark_maroon_).
maleta(muted_gray_,2,clear_gold_).
maleta(muted_gray_,3,plaid_gray_).
maleta(clear_brown_,5,shiny_tomato_).
maleta(clear_brown_,4,striped_tan_).
maleta(clear_brown_,5,vibrant_lavender_).
maleta(clear_brown_,1,pale_white_).
maleta(posh_crimson_,3,dim_yellow_).
maleta(posh_crimson_,4,shiny_turquoise_).
maleta(posh_crimson_,2,vibrant_purple_).
maleta(posh_crimson_,4,mirrored_aqua_).
maleta(plaid_black_,2,shiny_tan_).
maleta(plaid_black_,1,pale_olive_).
maleta(plaid_black_,2,wavy_tan_).
maleta(plaid_black_,1,clear_red_).
maleta(dark_crimson_,3,drab_fuchsia_).
maleta(dark_crimson_,5,faded_gold_).
maleta(pale_tan_,5,posh_black_).
maleta(wavy_bronze_,1,clear_lime_).
maleta(wavy_gold_,2,dull_lavender_).
maleta(wavy_gold_,1,bright_turquoise_).
maleta(wavy_gold_,4,striped_brown_).
maleta(wavy_gold_,5,drab_turquoise_).
maleta(pale_lime_,2,faded_cyan_).
maleta(pale_lime_,4,muted_salmon_).
maleta(pale_lime_,4,shiny_coral_).
maleta(pale_lime_,3,mirrored_green_).
maleta(dark_magenta_,4,faded_chartreuse_).
maleta(dark_magenta_,1,muted_brown_).
maleta(dark_magenta_,4,vibrant_salmon_).
maleta(dark_magenta_,2,dim_indigo_).
maleta(striped_purple_,3,mirrored_olive_).
maleta(dull_crimson_,2,clear_orange_).
maleta(dull_beige_,1,drab_turquoise_).
maleta(dull_beige_,1,dark_indigo_).
maleta(dull_beige_,1,dull_white_).
maleta(dotted_aqua_,4,dull_chartreuse_).
maleta(clear_purple_,2,muted_beige_).
maleta(clear_purple_,3,dull_black_).
maleta(light_crimson_,1,faded_brown_).
maleta(light_crimson_,1,vibrant_red_).
maleta(light_crimson_,4,wavy_lavender_).
maleta(light_crimson_,1,wavy_gray_).
maleta(clear_fuchsia_,1,dark_maroon_).
maleta(clear_fuchsia_,3,muted_salmon_).
maleta(muted_crimson_,5,light_lime_).
maleta(muted_crimson_,4,posh_plum_).
maleta(muted_crimson_,5,clear_fuchsia_).
maleta(muted_crimson_,1,wavy_turquoise_).
maleta(muted_purple_,3,dull_gray_).
maleta(muted_purple_,5,posh_gray_).
maleta(shiny_salmon_,5,faded_brown_).
maleta(shiny_salmon_,4,clear_chartreuse_).
maleta(plaid_lavender_,1,dim_lime_).
maleta(vibrant_indigo_,5,dim_tomato_).
maleta(vibrant_indigo_,2,striped_beige_).
maleta(vibrant_indigo_,2,mirrored_olive_).
maleta(mirrored_cyan_,3,plaid_coral_).
maleta(mirrored_cyan_,5,faded_teal_).
maleta(mirrored_cyan_,5,pale_indigo_).
maleta(mirrored_cyan_,3,bright_fuchsia_).
maleta(dim_yellow_,5,light_crimson_).
maleta(dim_yellow_,1,pale_tomato_).
maleta(dotted_chartreuse_,3,shiny_blue_).
maleta(light_beige_,3,bright_teal_).
maleta(light_beige_,1,pale_tomato_).
maleta(light_beige_,2,light_blue_).
maleta(dotted_olive_,3,bright_indigo_).
maleta(dotted_olive_,4,muted_fuchsia_).
maleta(pale_white_,1,vibrant_maroon_).
maleta(pale_white_,2,pale_tomato_).
maleta(pale_white_,2,bright_magenta_).
maleta(mirrored_yellow_,2,drab_brown_).
maleta(mirrored_yellow_,3,striped_salmon_).
maleta(mirrored_yellow_,4,clear_olive_).
maleta(mirrored_yellow_,1,dotted_black_).
maleta(light_olive_,2,bright_magenta_).
maleta(muted_tomato_,4,shiny_lavender_).
maleta(light_chartreuse_,5,light_plum_).
maleta(light_chartreuse_,4,light_olive_).
maleta(light_chartreuse_,3,dark_indigo_).
maleta(posh_purple_,2,wavy_crimson_).
maleta(bright_maroon_,4,faded_indigo_).
maleta(dull_blue_,3,dark_brown_).
maleta(dull_blue_,3,dim_indigo_).
maleta(dull_blue_,5,pale_silver_).
maleta(dull_blue_,1,mirrored_brown_).
maleta(light_coral_,5,clear_teal_).
maleta(bright_gray_,3,muted_black_).
maleta(bright_gray_,3,vibrant_cyan_).
maleta(posh_fuchsia_,3,clear_gold_).
maleta(posh_fuchsia_,1,dim_salmon_).
maleta(posh_fuchsia_,2,shiny_salmon_).
maleta(light_white_,3,dim_cyan_).
maleta(light_white_,5,clear_crimson_).
maleta(light_white_,3,dull_fuchsia_).
maleta(light_teal_,3,shiny_fuchsia_).
maleta(light_teal_,2,muted_white_).
maleta(light_teal_,3,shiny_black_).
maleta(plaid_salmon_,2,dotted_black_).
maleta(plaid_salmon_,2,dark_beige_).
maleta(plaid_salmon_,1,shiny_coral_).
maleta(wavy_black_,5,posh_olive_).
maleta(drab_gray_,3,mirrored_tomato_).
maleta(drab_gray_,3,light_crimson_).
maleta(dim_olive_,5,clear_chartreuse_).
maleta(bright_white_,2,mirrored_tan_).
maleta(bright_white_,1,pale_green_).
maleta(bright_white_,5,dull_magenta_).
maleta(bright_white_,5,plaid_lime_).
maleta(striped_olive_,3,muted_gold_).
maleta(faded_olive_,1,muted_indigo_).
maleta(pale_yellow_,5,light_olive_).
maleta(pale_yellow_,5,plaid_aqua_).
maleta(pale_yellow_,1,clear_white_).
maleta(pale_yellow_,5,faded_purple_).
maleta(dull_coral_,4,light_crimson_).
maleta(dull_coral_,5,shiny_aqua_).
maleta(dull_coral_,5,wavy_cyan_).
maleta(dull_coral_,3,dark_beige_).
maleta(vibrant_beige_,4,striped_olive_).
maleta(vibrant_beige_,5,clear_gold_).
maleta(dark_fuchsia_,1,pale_teal_).
maleta(dark_fuchsia_,4,dull_gray_).
maleta(drab_tomato_,4,mirrored_white_).
maleta(clear_crimson_,4,pale_tomato_).
maleta(clear_crimson_,3,wavy_gray_).
maleta(clear_crimson_,4,drab_blue_).
maleta(clear_crimson_,1,mirrored_olive_).
maleta(dotted_crimson_,1,plaid_crimson_).
maleta(dotted_crimson_,1,dark_crimson_).
maleta(dotted_crimson_,1,striped_beige_).
maleta(dotted_crimson_,4,pale_fuchsia_).
maleta(striped_black_,4,muted_maroon_).
maleta(shiny_bronze_,1,dotted_tan_).
maleta(shiny_bronze_,1,vibrant_beige_).
maleta(shiny_bronze_,5,faded_tomato_).
maleta(light_cyan_,no,other_).
maleta(posh_black_,2,dim_green_).
maleta(striped_gold_,3,drab_tan_).
maleta(faded_white_,4,pale_coral_).
maleta(drab_tan_,4,clear_gold_).
maleta(drab_tan_,5,drab_silver_).
maleta(light_tan_,2,dull_lime_).
maleta(light_tan_,1,muted_salmon_).
maleta(light_tan_,4,pale_beige_).
maleta(plaid_indigo_,3,plaid_salmon_).
maleta(plaid_indigo_,1,vibrant_maroon_).
maleta(faded_gold_,3,dark_coral_).
maleta(dark_salmon_,5,bright_gold_).
maleta(dark_salmon_,1,pale_white_).
maleta(plaid_bronze_,3,drab_gold_).
maleta(plaid_bronze_,4,dotted_black_).
maleta(shiny_black_,3,bright_magenta_).
maleta(shiny_black_,2,dark_indigo_).
maleta(shiny_black_,1,posh_plum_).
maleta(shiny_black_,5,drab_gold_).
maleta(pale_magenta_,1,clear_gold_).
maleta(pale_magenta_,5,posh_fuchsia_).
maleta(pale_magenta_,2,faded_cyan_).
cont(X,C,Y) :- maleta(X,C,Y), not(maleta(X,C,other_)).
cont(X,C,Y) :- maleta(X,A,Z), cont(Z,B,Y), C is A * B.
my_length([], 0).
my_length([_|Xs], L) :- my_length(Xs, L2), L is L2 + 1.
my_sum_elements([], 0).
my_sum_elements([X|Xs], S) :- my_sum_elements(Xs, S2), S is S2 + X.